### ISSUE TITLE
beer doesn't have calories

### ISSUE THREAD

**Issue by 93k00c3** [jruchel/calorie-counter#1]
no proof of beer having calories

**Comment by jruchel** [comment]
@93k00c3 Please provide proof for there being no proof before this is considered and/or implemented

**Comment by 93k00c3** [comment]
> @93k00c3 Please provide proof for there being no proof before this is considered and/or implemented

No.

**Comment by jruchel** [comment]
https://www.youtube.com/watch?v=3_lAb8m9MpI&ab_channel=KieranGrant

**Comment by jruchel** [comment]
https://www.youtube.com/watch?v=3_lAb8m9MpI&ab_channel=KieranGrant
